/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppUsersResultsIndexRouteImport } from './routes/_app/users-results/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppPublicApiManagementIndexRouteImport } from './routes/_app/public-api-management/index'
import { Route as AppContentManagementIndexRouteImport } from './routes/_app/content-management/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/_dashboard/index'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersResultsIndexRoute = AppUsersResultsIndexRouteImport.update({
  id: '/users-results/',
  path: '/users-results/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPublicApiManagementIndexRoute =
  AppPublicApiManagementIndexRouteImport.update({
    id: '/public-api-management/',
    path: '/public-api-management/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppContentManagementIndexRoute =
  AppContentManagementIndexRouteImport.update({
    id: '/content-management/',
    path: '/content-management/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/_dashboard/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppDashboardIndexRoute
  '/content-management': typeof AppContentManagementIndexRoute
  '/public-api-management': typeof AppPublicApiManagementIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/users-results': typeof AppUsersResultsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppDashboardIndexRoute
  '/content-management': typeof AppContentManagementIndexRoute
  '/public-api-management': typeof AppPublicApiManagementIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/users-results': typeof AppUsersResultsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/_dashboard/': typeof AppDashboardIndexRoute
  '/_app/content-management/': typeof AppContentManagementIndexRoute
  '/_app/public-api-management/': typeof AppPublicApiManagementIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/users-results/': typeof AppUsersResultsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/content-management'
    | '/public-api-management'
    | '/settings'
    | '/users-results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/content-management'
    | '/public-api-management'
    | '/settings'
    | '/users-results'
  id:
    | '__root__'
    | '/_app'
    | '/_app/_dashboard/'
    | '/_app/content-management/'
    | '/_app/public-api-management/'
    | '/_app/settings/'
    | '/_app/users-results/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users-results/': {
      id: '/_app/users-results/'
      path: '/users-results'
      fullPath: '/users-results'
      preLoaderRoute: typeof AppUsersResultsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/public-api-management/': {
      id: '/_app/public-api-management/'
      path: '/public-api-management'
      fullPath: '/public-api-management'
      preLoaderRoute: typeof AppPublicApiManagementIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/content-management/': {
      id: '/_app/content-management/'
      path: '/content-management'
      fullPath: '/content-management'
      preLoaderRoute: typeof AppContentManagementIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_dashboard/': {
      id: '/_app/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppContentManagementIndexRoute: typeof AppContentManagementIndexRoute
  AppPublicApiManagementIndexRoute: typeof AppPublicApiManagementIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppUsersResultsIndexRoute: typeof AppUsersResultsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppContentManagementIndexRoute: AppContentManagementIndexRoute,
  AppPublicApiManagementIndexRoute: AppPublicApiManagementIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppUsersResultsIndexRoute: AppUsersResultsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
